name: patchtst_baseline
data:
  source: sharadar_sep_daily
  features: [open, high, low, close, volume]
  target: close
  lookback: 128
  horizon: 16
  batch_size: 64
  val_fraction: 0.1
  test_fraction: 0.1
model:
  type: patchtst
  input_dim: 5
  patch_length: 16
  stride: 8
  d_model: 128
  nheads: 8
  depth: 4
optimizer:
  lr: 0.0001
  weight_decay: 0.0001
trainer:
  max_epochs: 50
  accelerator: auto
  precision: 16-mixed
  gradient_clip_val: 1.0
output_dir: artifacts/patchtst
